package applet;

public class UtilMusig {

    // Generated by GitHub Copilot
    public static short bytesToShort(byte[] byteTupple, short offset) {

        if (byteTupple == null || (short) byteTupple.length < offset + 2) {
            return (short) -1;
        }

        return (short) ((byteTupple[offset] << 8) | (byteTupple[(short) (offset + 1)] & 0xFF));
    }

    // Generated by GitHub Copilot
    public static byte[] hexStringToByteArray(String s) {
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
                    + Character.digit(s.charAt(i+1), 16));
        }
        return data;
    }
}
