package applet;

public class UtilMusig {

    // Generated by GitHub Copilot
    public static short bytesToShort(byte[] byteTupple, short offset) {

        if (byteTupple == null || (short) byteTupple.length < offset + 2) {
            return (short) -1;
        }

        return (short) ((byteTupple[offset] << 8) | (byteTupple[(short) (offset + 1)] & 0xFF));
    }
}
