# Manual applet release

name: Manual applet release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Tag name for the release
        required: true
      release_name:
        description: Release name
        required: true
      release_description:
        description: Release description
        required: false

jobs:
  build-cap:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.release_name }}
          body: ${{ inputs.release_description }}
          draft: true
          prerelease: false

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build JavaCard applet with Gradle Wrapper
        run: ./gradlew buildJavaCard

      - name: Check if build exists
        run: |
          [ -e applet/build/javacard/applet.cap ] || exit 1

      - name: Create Musig2JC applet artifact
        uses: actions/upload-artifact@v4
        with:
          name: applet.cap
          path:
            applet/build/javacard/applet.cap

      - name: Upload Musig2JC applet artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./applet/build/javacard/applet.cap
          asset_name: applet.cap
          asset_content_type: application/java-archive