# Manual applet release

name: Manual applet release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Tag name for the release
        required: true
      release_name:
        description: Release name
        required: true

jobs:
  build-cap:

    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.release_name }}
          body: |
            Release description
          draft: true
          prerelease: false

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build JavaCard applet with Gradle Wrapper
        run: ./gradlew buildJavaCard

      - name: Upload CAP artifact
        uses: actions/upload-artifact@v4
        with:
          name: Musig2JC Applet
          path:
            build/javacard/applet.cap